---
# Variables del rol Nginx (no sensibles, se versionan en Git)

# Dominio principal
nginx_domain: "jiahaoye-tfg.duckdns.org"

# Backends de los servicios
nginx_nextcloud_backend: "http://192.168.100.13:8080"
nginx_vaultwarden_backend: "http://192.168.100.14:8080"
nginx_homer_backend: "http://192.168.100.16:8080"

# Redes permitidas para acceder a Nextcloud
nginx_allowed_networks:
  - "10.0.0.0/24"        # Red VPN WireGuard
  - "192.168.100.0/24"   # Red interna de VMs
  - "192.168.1.0/24"     # Red LAN (NAT)

# Rate limiting
nginx_rate_limit_burst: 200

