[nextcloud]
192.168.100.13 vm_hostname=nextcloud

[vaultwarden]
192.168.100.14 vm_hostname=vaultwarden

[postgresql]
192.168.100.15 vm_hostname=postgresql

[nginx]
192.168.100.12 vm_hostname=nginx-proxy

[wireguard]
192.168.100.11 vm_hostname=wireguard-vpn

[homer]
192.168.100.16 vm_hostname=homer-dashboard

[all:vars]
ansible_user=jiahao
ansible_ssh_private_key_file=~/.ssh/id_ed25519

