---
- name: Asegurar que Nginx está instalado
  apt:
    name: nginx
    state: present

- name: Asegurar que Nginx está corriendo
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Copiar configuración de rate limiting
  copy:
    src: rate_limit.conf
    dest: /etc/nginx/conf.d/rate_limit.conf
    owner: root
    group: root
    mode: "0644"
  notify: recargar nginx

- name: Configurar proxy inverso (cabeceras seguridad + rate limiting)
  template:
    src: jiahaoye-tfg.duckdns.org.j2
    dest: /etc/nginx/sites-available/{{ nginx_domain }}
    owner: root
    group: root
    mode: "0644"
  notify: recargar nginx

- name: Activar sitio en sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ nginx_domain }}
    dest: /etc/nginx/sites-enabled/{{ nginx_domain }}
    state: link
  notify: recargar nginx

- name: Abrir puerto HTTP en UFW
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Abrir puerto HTTPS en UFW
  ufw:
    rule: allow
    port: "443"
    proto: tcp
